// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLno1NCPNj8WIYvZUTByYfvJHGQ8WJPg',
    appId: '1:225299124033:web:df4b8ce726ca21fb4d9bc0',
    messagingSenderId: '225299124033',
    projectId: 'mynotes-flutter-app-ns',
    authDomain: 'mynotes-flutter-app-ns.firebaseapp.com',
    storageBucket: 'mynotes-flutter-app-ns.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0M5FzoEeDNibdyw2epq560086py11Z6Q',
    appId: '1:225299124033:android:2dfc993ea9b689854d9bc0',
    messagingSenderId: '225299124033',
    projectId: 'mynotes-flutter-app-ns',
    storageBucket: 'mynotes-flutter-app-ns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8nhRrtUfyu3uyil1yoDw3SkGug-RDM8',
    appId: '1:225299124033:ios:a6dfaf8ac466072a4d9bc0',
    messagingSenderId: '225299124033',
    projectId: 'mynotes-flutter-app-ns',
    storageBucket: 'mynotes-flutter-app-ns.appspot.com',
    iosBundleId: 'com.codeatble.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR8nhRrtUfyu3uyil1yoDw3SkGug-RDM8',
    appId: '1:225299124033:ios:b1ea213b9eea16d64d9bc0',
    messagingSenderId: '225299124033',
    projectId: 'mynotes-flutter-app-ns',
    storageBucket: 'mynotes-flutter-app-ns.appspot.com',
    iosBundleId: 'com.codeatble.mynotes.RunnerTests',
  );
}
